#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += odm
AB_OTA_PARTITIONS += product
AB_OTA_PARTITIONS += system
AB_OTA_PARTITIONS += system_ext
AB_OTA_PARTITIONS += vendor
AB_OTA_PARTITIONS += vendor_dlkm
BOARD_USES_RECOVERY_AS_BOOT := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a78

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := parrot

# Kernel
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := gki_defconfig
TARGET_KERNEL_SOURCE := kernel/xiaomi/garnet

BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_BASE := 0x00000000

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 9653190656
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions

BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += odm
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += system
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += product
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += system_ext
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor_dlkm

BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9653190656