#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += odm
AB_OTA_PARTITIONS += product
AB_OTA_PARTITIONS += system
AB_OTA_PARTITIONS += system_ext
AB_OTA_PARTITIONS += vendor
AB_OTA_PARTITIONS += vendor_dlkm
BOARD_USES_RECOVERY_AS_BOOT := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a78

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := parrot

# Kernel
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_BASE := 0x00000000

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 9653190656
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions

BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += odm
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += system
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += product
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += system_ext
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST += vendor_dlkm

# Partitions
BOARD_ODMIMAGE_PARTITION_SIZE := 31354880 			# 29.90 MB
BOARD_BOOTIMAGE_PARTITION_SIZE := 201326592 		# 192.00 MB
BOARD_VENDORIMAGE_PARTITION_SIZE := 1415499776 		# 1.32 GB
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 3312644096 	# 3.09 GB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1018634240 		# 971.44 MB
BOARD_VENDOR_DLKMIMAGE_PARTITION_SIZE := 34992128 	# 33.37 MB
BOARD_SYSTEM_EXTIMAGE_PARTITION_SIZE := 648847360 	# 618.79 MB

# Copy out
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_BOOT := boot
TARGET_COPY_OUT_SYSTEM := system
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

# FS Type
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_BOOTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Enable chained vbmeta for recovery
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem

# Enable chained vbmeta for vendor boot
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX := 1
BOARD_AVB_VENDOR_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_VENDOR_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem